use super::support::*;

#[test]
fn quickstart_no_run_prints_host_manifest_status_and_next_check() {
    let dir = tempfile::tempdir().unwrap();
    let tarball = write_release_tarball(&dir);
    let paths = install_paths(&dir, "human-next");

    let output = m80()
        .args(quickstart_no_run_args(&tarball, &paths))
        .output()
        .unwrap();

    assert!(
        output.status.success(),
        "quickstart --no-run failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains(&format!(
            "host manifest: {} (not generated by --no-run)",
            paths.dst.join("host-binaries.manifest.json").display()
        )),
        "quickstart --no-run should name the missing host manifest state; stderr={stderr}"
    );
    assert!(
        stderr.contains("Next check:\n  m80 preflight"),
        "quickstart --no-run should name the next diagnostic command; stderr={stderr}"
    );
}

#[test]
fn quickstart_rejects_bundled_host_binaries_manifest() {
    let dir = tempfile::tempdir().unwrap();
    let tarball = write_release_tarball_with_bundled_host_manifest(&dir);
    let dst = dir.path().join("host-manifest-dst");
    let run_root = dir.path().join("host-manifest-run");

    let output = m80()
        .args([
            "quickstart",
            "--artifact-url",
            &format!("file://{}", tarball.display()),
            "--artifact-dir",
            dst.to_str().unwrap(),
            "--run-root",
            run_root.to_str().unwrap(),
            "--no-run",
        ])
        .output()
        .unwrap();

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("host-binaries.manifest.json"),
        "quickstart should explain the forbidden bundled host manifest; stderr={stderr}"
    );
    assert!(
        !dst.exists(),
        "quickstart must not install artifacts after seeing a bundled host manifest"
    );
}

#[test]
fn quickstart_rejects_nested_bundled_host_binaries_manifest() {
    let dir = tempfile::tempdir().unwrap();
    let tarball = write_release_tarball_with_nested_bundled_host_manifest(&dir);
    let dst = dir.path().join("nested-host-manifest-dst");
    let run_root = dir.path().join("nested-host-manifest-run");

    let output = m80()
        .args([
            "quickstart",
            "--artifact-url",
            &format!("file://{}", tarball.display()),
            "--artifact-dir",
            dst.to_str().unwrap(),
            "--run-root",
            run_root.to_str().unwrap(),
            "--no-run",
        ])
        .output()
        .unwrap();

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("host-binaries.manifest.json"),
        "quickstart should reject nested bundled host manifests; stderr={stderr}"
    );
    assert!(
        !dst.exists(),
        "quickstart must not install artifacts after seeing a nested host manifest"
    );
}

#[test]
fn quickstart_rejects_bundled_operator_host_prerequisites() {
    for relpath in [
        "firecracker",
        "nested/jailer",
        "nested/firecracker-seccomp-filter.bin",
    ] {
        let dir = tempfile::tempdir().unwrap();
        let tarball = write_release_tarball_with_extra_file(&dir, relpath);
        let dst = dir.path().join("host-prereq-dst");
        let run_root = dir.path().join("host-prereq-run");

        let output = m80()
            .args([
                "quickstart",
                "--artifact-url",
                &format!("file://{}", tarball.display()),
                "--artifact-dir",
                dst.to_str().unwrap(),
                "--run-root",
                run_root.to_str().unwrap(),
                "--no-run",
            ])
            .output()
            .unwrap();

        assert!(
            !output.status.success(),
            "quickstart should reject bundled host prerequisite {relpath}"
        );
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains(
                std::path::Path::new(relpath)
                    .file_name()
                    .unwrap()
                    .to_str()
                    .unwrap()
            ),
            "quickstart should name forbidden host prerequisite {relpath}; stderr={stderr}"
        );
        assert!(
            stderr.contains("operator-provided host prerequisites"),
            "quickstart should explain the host-prereq ownership policy; stderr={stderr}"
        );
        assert!(
            !dst.exists(),
            "quickstart must not install artifacts after seeing bundled host prerequisite {relpath}"
        );
    }
}
