#!/usr/bin/env python3
"""Regenerate the docs freshness status from a public-access release receipt."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import tempfile
from typing import Any

import freshness_status
import release_public_access_receipt
import stable_release_channel


BUILDER_RUN_RE = re.compile(r"/actions/runs/([0-9]+)(?:/|$)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--receipt",
        type=Path,
        default=Path("docs/behaviors/release/release-readiness-public-access.json"),
        help="public-access receipt JSON generated by release_public_access_receipt.py",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("docs/behaviors/release/freshness-status-docs.json"),
        help="freshness status JSON to write",
    )
    parser.add_argument(
        "--artifact-root",
        type=Path,
        help="root used for relative proof artifact paths; defaults to the receipt directory",
    )
    parser.add_argument(
        "--docs-root",
        type=Path,
        default=Path("."),
        help="repository root used for command inventory digest validation",
    )
    parser.add_argument(
        "--workflow-run-id",
        help="release workflow run id; defaults to the run id in release_build.builder_identity",
    )
    parser.add_argument(
        "--expected-stable-tag",
        help="highest expected stable tag; defaults to the receipt expected_stable_tag/release_tag",
    )
    parser.add_argument(
        "--safety-floor",
        type=Path,
        help="optional safety_floor JSON object to embed after validation",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    receipt_path = args.receipt.resolve()
    artifact_root = (args.artifact_root or args.receipt.parent).resolve()
    docs_root = args.docs_root.resolve()
    out_path = args.out

    receipt = read_json(receipt_path)
    release_public_access_receipt.verify_receipt(
        receipt,
        expected_repository=require_str(receipt, "repository"),
        expected_release_tag=require_str(receipt, "release_tag"),
        expected_commit_sha=require_str(receipt, "commit_sha"),
    )
    status = build_status(
        receipt,
        receipt_path=receipt_path,
        artifact_root=artifact_root,
        docs_root=docs_root,
        workflow_run_id=args.workflow_run_id,
        expected_stable_tag=args.expected_stable_tag,
        safety_floor_path=args.safety_floor.resolve() if args.safety_floor else None,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=out_path.parent,
        prefix=f".{out_path.name}.",
        suffix=".tmp",
        delete=False,
    ) as candidate:
        candidate_path = Path(candidate.name)
        json.dump(status, candidate, indent=2, sort_keys=True)
        candidate.write("\n")
    try:
        freshness_status.validate_freshness_status(
            candidate_path,
            artifact_root=artifact_root,
            docs_root=docs_root,
        )
        candidate_path.chmod(0o644)
        candidate_path.replace(out_path)
    finally:
        candidate_path.unlink(missing_ok=True)
    print(f"updated freshness status from public-access receipt: {out_path}")
    return 0


def build_status(
    receipt: dict[str, Any],
    *,
    receipt_path: Path,
    artifact_root: Path,
    docs_root: Path,
    workflow_run_id: str | None,
    expected_stable_tag: str | None,
    safety_floor_path: Path | None,
) -> dict[str, Any]:
    repository = require_str(receipt, "repository")
    owner, repo = split_repository(repository)
    release_tag = require_str(receipt, "release_tag")
    expected_tag = expected_stable_tag or receipt.get("expected_stable_tag") or release_tag
    receipt_ref = relative_artifact_path(artifact_root, receipt_path)
    receipt_sha = "sha256:" + hashlib.sha256(receipt_path.read_bytes()).hexdigest()
    latest = require_dict(require_dict(receipt, "installer_downloads"), "latest_install")
    pinned = require_dict(require_dict(receipt, "installer_downloads"), "pinned_install")
    safety_floor = (
        read_safety_floor(safety_floor_path)
        if safety_floor_path is not None
        else empty_safety_floor(require_str(receipt, "verification_time"))
    )
    return {
        "schema_version": freshness_status.SCHEMA_VERSION,
        "generated_at": require_str(receipt, "verification_time"),
        "status": "public_green",
        "owner": owner,
        "repo": repo,
        "resolved_latest_tag": require_str(receipt, "resolved_latest_tag"),
        "expected_highest_stable_tag": require_str({"expected_tag": expected_tag}, "expected_tag"),
        "latest_install_url": require_str(receipt, "latest_install_url"),
        "pinned_install_url": require_str(receipt, "pinned_install_url"),
        "proof_artifacts": [
            {
                "kind": "latest-and-pinned-url-proof",
                "path": receipt_ref,
                "sha256": receipt_sha,
                "artifact_class": "public",
            }
        ],
        "proof_substrate": "public-unauthenticated",
        "workflow_run_id": workflow_run_id or workflow_run_id_from_receipt(receipt),
        "source_commit": require_str(receipt, "commit_sha"),
        "checked_command_inventory_digest": freshness_status.command_inventory_digest(docs_root),
        "install_url_proofs": [
            install_url_proof("latest-install", receipt, latest, receipt_ref),
            install_url_proof("pinned-install", receipt, pinned, receipt_ref),
        ],
        "public_assets": public_assets(receipt, release_tag),
        "safety_floor": safety_floor,
    }


def install_url_proof(kind: str, receipt: dict[str, Any], row: dict[str, Any], receipt_ref: str) -> dict[str, Any]:
    url_field = "latest_install_url" if kind == "latest-install" else "pinned_install_url"
    return {
        "kind": kind,
        "url": require_str(receipt, url_field),
        "final_url": require_str(row, "final_url"),
        "http_status": require_int(row, "http_status"),
        "unauthenticated": True,
        "artifact_path": receipt_ref,
    }


def public_assets(receipt: dict[str, Any], release_tag: str) -> list[dict[str, Any]]:
    rows = require_list(receipt, "downloaded_assets")
    by_name: dict[str, dict[str, Any]] = {}
    for row in rows:
        if not isinstance(row, dict):
            raise ValueError("downloaded asset must be an object")
        by_name[require_str(row, "name")] = row
    assets = []
    for name in sorted(stable_release_channel.REQUIRED_PUBLIC_ASSETS):
        row = by_name.get(name)
        if row is None:
            raise ValueError(f"public-access receipt missing downloaded asset: {name}")
        assets.append(
            {
                "name": name,
                "role": stable_release_channel.public_asset_role(name),
                "url": f"https://github.com/{require_str(receipt, 'repository')}/releases/download/{release_tag}/{name}",
                "sha256": require_str(row, "sha256"),
                "size_bytes": require_int(row, "size_bytes"),
            }
        )
    return assets


def empty_safety_floor(published_at: str) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "published_at": published_at,
        "minimum_safe_tag": None,
        "yanked_releases": [],
    }


def read_safety_floor(path: Path) -> dict[str, Any]:
    value = read_json(path)
    required = {"schema_version", "published_at", "minimum_safe_tag", "yanked_releases"}
    actual = set(value)
    if actual != required:
        missing = ", ".join(sorted(required - actual)) or "<none>"
        extra = ", ".join(sorted(actual - required)) or "<none>"
        raise ValueError(f"safety-floor input fields mismatch: missing {missing}; extra {extra}")
    return value


def workflow_run_id_from_receipt(receipt: dict[str, Any]) -> str:
    release_build = require_dict(receipt, "release_build")
    identity = release_build.get("builder_identity")
    if isinstance(identity, str):
        match = BUILDER_RUN_RE.search(identity)
        if match is not None:
            return match.group(1)
    raise ValueError("missing --workflow-run-id and release_build.builder_identity has no actions run id")


def relative_artifact_path(root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError as exc:
        raise ValueError(f"{path} is not under artifact root {root}") from exc


def split_repository(value: str) -> tuple[str, str]:
    parts = value.split("/", 1)
    if len(parts) != 2 or not all(parts):
        raise ValueError(f"repository must be owner/repo, got {value!r}")
    return parts[0], parts[1]


def read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def require_dict(obj: dict[str, Any], key: str) -> dict[str, Any]:
    value = obj.get(key)
    if not isinstance(value, dict):
        raise ValueError(f"{key} must be an object")
    return value


def require_list(obj: dict[str, Any], key: str) -> list[Any]:
    value = obj.get(key)
    if not isinstance(value, list):
        raise ValueError(f"{key} must be a list")
    return value


def require_str(obj: dict[str, Any], key: str) -> str:
    value = obj.get(key)
    if not isinstance(value, str) or not value:
        raise ValueError(f"{key} must be a nonempty string")
    return value


def require_int(obj: dict[str, Any], key: str) -> int:
    value = obj.get(key)
    if not isinstance(value, int):
        raise ValueError(f"{key} must be an integer")
    return value


if __name__ == "__main__":
    raise SystemExit(main())
